=== ironhacker-sadigova/Inventory/scripts/build/populate/Unit/data/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/extension"
        xmlns:tns="http://www.example.org/extension"
        elementFormDefault="qualified">


    <element name="xml">
        <complexType>
            <sequence>
                <element name="extension" type="tns:extension" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="extension">
        <sequence>
            <element name="name" type="string"/>
            <element name="symbol" type="string"/>
            <element name="multiplier" type="float"/>
        </sequence>
        <attribute name="ref" type="tns:refType" use="required"/>
    </complexType>

    <simpleType name="refType">
        <restriction base="string">
            <pattern value="([a-z0-9_-])*"/>
        </restriction>
    </simpleType>
</schema>

=== ironhacker-sadigova/Inventory/scripts/build/populate/Unit/data/extension.xml
<?xml version="1.0" encoding="UTF-8"?>

<xml xmlns="http://www.example.org/extension"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.example.org/extension extension.xsd ">

    <!-- Pour toutes les conventions relatives à l'ordre entre les objets, le choix des identifiants, des symboles, et des libellés, voir specs -->

    <extension ref="co2e">
        <name>équivalent CO2</name>
        <symbol>équ. CO2</symbol>
        <multiplier>1</multiplier>
    </extension>

    <extension ref="ce">
        <name>équivalent carbone</name>
        <symbol>équ. C</symbol>
        <multiplier>3.666666667</multiplier>
    </extension>

</xml>
