=== ironhacker-sadigova/Inventory/scripts/build/populate/Unit/data/extendedUnit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/extendedUnit"
        xmlns:tns="http://www.example.org/extendedUnit"
        elementFormDefault="qualified">

    <element name="xml">
        <complexType>
            <sequence>
                <element name="extendedUnit" type="tns:extendedUnit" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="extendedUnit">
        <sequence>
            <element name="name" type="string"/>
            <element name="derivedQuantityRef" type="string"/>
            <element name="quantityExtensionRef" type="string"/>
        </sequence>
        <attribute name="ref" type="tns:refType" use="required"/>
    </complexType>

    <simpleType name="refType">
        <restriction base="string">
            <pattern value="([a-z0-9_-])*"/>
        </restriction>
    </simpleType>
</schema>

=== ironhacker-sadigova/Inventory/scripts/build/populate/Unit/data/extendedUnit.xml
<?xml version="1.0" encoding="UTF-8"?>

<xml xmlns="http://www.example.org/extendedUnit"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.example.org/extendedUnit extendedUnit.xsd ">

    <extendedUnit ref="masse_equivalent_gaz_effet_serre">
        <name>Masse équivalent gaz à effet de serre</name>
        <derivedQuantityRef>kg</derivedQuantityRef>
        <quantityExtensionRef>co2e</quantityExtensionRef>
    </extendedUnit>

    <extendedUnit ref="masse_equivalent_gaz_effet_serre">
        <name>Masse équivalent gaz à effet de serre</name>
        <derivedQuantityRef>g</derivedQuantityRef>
        <quantityExtensionRef>co2e</quantityExtensionRef>
    </extendedUnit>

    <extendedUnit ref="masse_equivalent_gaz_effet_serre">
        <name>Masse équivalent gaz à effet de serre</name>
        <derivedQuantityRef>t</derivedQuantityRef>
        <quantityExtensionRef>co2e</quantityExtensionRef>
    </extendedUnit>

    <extendedUnit ref="masse_equivalent_gaz_effet_serre">
        <name>Masse équivalent gaz à effet de serre</name>
        <derivedQuantityRef>kg</derivedQuantityRef>
        <quantityExtensionRef>ce</quantityExtensionRef>
    </extendedUnit>

    <extendedUnit ref="masse_equivalent_gaz_effet_serre">
        <name>Masse équivalent gaz à effet de serre</name>
        <derivedQuantityRef>g</derivedQuantityRef>
        <quantityExtensionRef>ce</quantityExtensionRef>
    </extendedUnit>

    <extendedUnit ref="masse_equivalent_gaz_effet_serre">
        <name>Masse équivalent gaz à effet de serre</name>
        <derivedQuantityRef>t</derivedQuantityRef>
        <quantityExtensionRef>ce</quantityExtensionRef>
    </extendedUnit>

</xml>
